# Generated by Django 3.2.9 on 2021-11-10 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(default=0)),
                ('titulo', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=30)),
                ('editorial', models.CharField(max_length=60)),
                ('num_pags', models.IntegerField(default=0)),
                ('libro_id_autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_rest.autor')),
            ],
        ),
    ]
